<a href="https://colab.research.google.com/github/ricecakeblack/myRepoTest/blob/main/6_numpy_broadcasting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

## 1. Broadcasting

## 1-1. 숫자의 연산 (단일)

In [ ]:
a = np.array([[1, 2, 3],
              [2, 3, 4]])

In [ ]:
b = np.array([[3, 3, 3],
              [3, 3, 3]])

In [ ]:
a + b

array([[4, 5, 6],
       [5, 6, 7]])

In [ ]:
# broadcast의 +연산은 행렬의 모든 요소에 동일한 값을 더한다.
a + 3 #행렬과 숫자의 연산은 broadcast 전체(행렬,배열)에다 연산을 해줌

array([[4, 5, 6],
       [5, 6, 7]])

In [ ]:
a - 3

array([[-2, -1,  0],
       [-1,  0,  1]])

In [ ]:
a * 3

array([[ 3,  6,  9],
       [ 6,  9, 12]])

In [ ]:
a / 3

array([[0.33333333, 0.66666667, 1.        ],
       [0.66666667, 1.        , 1.33333333]])

### 1-2. array(배열)의 브로드캐스팅

오리지널 array의 shape가 유지됨을 잘 보세요

In [ ]:
import numpy as np

In [ ]:
a = np.array([[1, 2, 3],
              [2, 3, 4]])

In [ ]:
b = np.array([[1],
              [2]])

In [ ]:
a.shape, b.shape

((2, 3), (2, 1))

In [ ]:
b * a

array([[1, 2, 3],
       [4, 6, 8]])

In [ ]:
a = np.array([[1, 2, 3],
              [2, 3, 4]])

In [ ]:
b = np.array([1, 2, 3])

In [ ]:
a * b